# Generated by Django 4.0.4 on 2022-04-29 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('abc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book1.thing')),
            ],
        ),
    ]
