# Generated by Django 4.0.4 on 2022-04-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0002_expansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansion',
            name='active',
            field=models.BooleanField(default=False, help_text='Выберите статус', verbose_name='Активен'),
        ),
    ]
