# Generated by Django 4.0.4 on 2022-04-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введи название', max_length=100, unique=True, verbose_name='Название')),
                ('discription', models.TextField(default='Какая-то фигня', max_length=100)),
                ('mail', models.EmailField(help_text='Введи mail', max_length=254, null=True)),
                ('url', models.URLField(help_text='Введи URL', null=True)),
                ('online', models.BooleanField(default=True)),
                ('age', models.IntegerField(null=True)),
                ('visit', models.DateField(auto_now=True)),
                ('activity', models.CharField(choices=[('Нету', (('z', 'Зашел'), ('v', 'Вышел'))), ('Есть', (('u', 'Ушел'),))], default='u', max_length=1)),
                ('reason', models.CharField(choices=[(None, 'Выберите че-то'), ('b', 'Куплю'), ('s', 'Продам')], default='s', max_length=1)),
                ('not_reason', models.SmallIntegerField(choices=[(None, 'Выберите че-то'), (1, 'Не Куплю'), (2, 'Не Продам')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[(1, 'Электрик'), (2, 'Сварщик'), (3, 'Конструктор'), (4, 'Пилот'), (5, 'Проект менеджер'), (6, 'Строитель')], default=1, help_text='Выберите профессию', max_length=100, unique=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models1.poduct')),
            ],
        ),
    ]
