# Generated by Django 4.0.4 on 2022-04-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models1', '0006_alter_profession_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='human',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='models1.poduct'),
        ),
    ]
