# Generated by Django 4.0.4 on 2022-05-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_magazin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_open', models.TimeField(help_text='Время работы')),
                ('time_close', models.TimeField(help_text='Время работы')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.magazin')),
            ],
        ),
    ]
